name: Flower App CI
on:
  push:
    branches:
    - main
env:
  TAG: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.TAG }}
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Setup kubectl
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBECONFIG }}
        kubectl-version: v1.22.0
    - name: Set image tag
      run: |
        sed -i 's|__TAG__|"${{ env.TAG }}"|g' k8s/deployment.yaml
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Apply k8s resources
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
      




